FROM node:16-alpine as builder
RUN npm install -g npm@7.11.2
WORKDIR /app
COPY ["package.json", "yarn.lock", "./"]
RUN yarn install
COPY . .
RUN yarn build

FROM nginx:1.18.0
COPY --from=builder /app/build /usr/share/nginx/html
RUN rm -f /etc/nginx/conf.d/*
ADD nginx.conf /etc/nginx/myapp.conf
CMD /usr/sbin/nginx -g 'daemon off;' -c /etc/nginx/myapp.conf
